/*
 * traQ v3
 *
 * traQ v3 API
 *
 * The version of the OpenAPI document: 3.0
 * 
 * Generated by: https://openapi-generator.tech
 */

/// BotTokens : BOTのトークン情報



#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct BotTokens {
    /// Verification Token
    #[serde(rename = "verificationToken")]
    pub verification_token: String,
    /// BOTアクセストークン
    #[serde(rename = "accessToken")]
    pub access_token: String,
}

impl BotTokens {
    /// BOTのトークン情報
    pub fn new(verification_token: String, access_token: String) -> BotTokens {
        BotTokens {
            verification_token,
            access_token,
        }
    }
}


