/*
 * traQ v3
 *
 * traQ v3 API
 *
 * The version of the OpenAPI document: 3.0
 * 
 * Generated by: https://openapi-generator.tech
 */

/// ChannelList : GET /channelsレスポンス



#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct ChannelList {
    /// パブリックチャンネルの配列
    #[serde(rename = "public")]
    pub public: Vec<crate::models::Channel>,
    /// ダイレクトメッセージチャンネルの配列
    #[serde(rename = "dm", skip_serializing_if = "Option::is_none")]
    pub dm: Option<Vec<crate::models::DmChannel>>,
}

impl ChannelList {
    /// GET /channelsレスポンス
    pub fn new(public: Vec<crate::models::Channel>) -> ChannelList {
        ChannelList {
            public,
            dm: None,
        }
    }
}


