/*
 * traQ v3
 *
 * traQ v3 API
 *
 * The version of the OpenAPI document: 3.0
 * 
 * Generated by: https://openapi-generator.tech
 */

/// ChannelTopic : チャンネルトピック



#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct ChannelTopic {
    /// トピック
    #[serde(rename = "topic")]
    pub topic: String,
}

impl ChannelTopic {
    /// チャンネルトピック
    pub fn new(topic: String) -> ChannelTopic {
        ChannelTopic {
            topic,
        }
    }
}


