/*
 * traQ v3
 *
 * traQ v3 API
 *
 * The version of the OpenAPI document: 3.0
 * 
 * Generated by: https://openapi-generator.tech
 */

/// ForcedNotificationChangedEvent : チャンネル強制通知状態変更イベント



#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct ForcedNotificationChangedEvent {
    /// 変更者UUID
    #[serde(rename = "userId")]
    pub user_id: uuid::Uuid,
    /// 変更後強制通知状態
    #[serde(rename = "force")]
    pub force: bool,
}

impl ForcedNotificationChangedEvent {
    /// チャンネル強制通知状態変更イベント
    pub fn new(user_id: uuid::Uuid, force: bool) -> ForcedNotificationChangedEvent {
        ForcedNotificationChangedEvent {
            user_id,
            force,
        }
    }
}


