/*
 * traQ v3
 *
 * traQ v3 API
 *
 * The version of the OpenAPI document: 3.0
 * 
 * Generated by: https://openapi-generator.tech
 */


/// 
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum OAuth2ResponseType {
    #[serde(rename = "code")]
    Code,
    #[serde(rename = "token")]
    Token,
    #[serde(rename = "none")]
    None,

}

impl ToString for OAuth2ResponseType {
    fn to_string(&self) -> String {
        match self {
            Self::Code => String::from("code"),
            Self::Token => String::from("token"),
            Self::None => String::from("none"),
        }
    }
}

impl Default for OAuth2ResponseType {
    fn default() -> OAuth2ResponseType {
        Self::Code
    }
}




