/*
 * traQ v3
 *
 * traQ v3 API
 *
 * The version of the OpenAPI document: 3.0
 * 
 * Generated by: https://openapi-generator.tech
 */

/// OAuth2Scope : OAuth2スコープ

/// OAuth2スコープ
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum OAuth2Scope {
    #[serde(rename = "read")]
    Read,
    #[serde(rename = "write")]
    Write,
    #[serde(rename = "manage_bot")]
    ManageBot,

}

impl ToString for OAuth2Scope {
    fn to_string(&self) -> String {
        match self {
            Self::Read => String::from("read"),
            Self::Write => String::from("write"),
            Self::ManageBot => String::from("manage_bot"),
        }
    }
}

impl Default for OAuth2Scope {
    fn default() -> OAuth2Scope {
        Self::Read
    }
}




