/*
 * traQ v3
 *
 * traQ v3 API
 *
 * The version of the OpenAPI document: 3.0
 * 
 * Generated by: https://openapi-generator.tech
 */

/// PatchStampRequest : スタンプ情報変更リクエスト



#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct PatchStampRequest {
    /// スタンプ名
    #[serde(rename = "name", skip_serializing_if = "Option::is_none")]
    pub name: Option<String>,
    /// 作成者UUID
    #[serde(rename = "creatorId", skip_serializing_if = "Option::is_none")]
    pub creator_id: Option<uuid::Uuid>,
}

impl PatchStampRequest {
    /// スタンプ情報変更リクエスト
    pub fn new() -> PatchStampRequest {
        PatchStampRequest {
            name: None,
            creator_id: None,
        }
    }
}


