/*
 * traQ v3
 *
 * traQ v3 API
 *
 * The version of the OpenAPI document: 3.0
 * 
 * Generated by: https://openapi-generator.tech
 */

/// PatchMeRequest : 自分のユーザー情報変更リクエスト



#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct PatchMeRequest {
    /// 新しい表示名
    #[serde(rename = "displayName", skip_serializing_if = "Option::is_none")]
    pub display_name: Option<String>,
    /// TwitterID
    #[serde(rename = "twitterId", skip_serializing_if = "Option::is_none")]
    pub twitter_id: Option<String>,
    /// 自己紹介(biography)
    #[serde(rename = "bio", skip_serializing_if = "Option::is_none")]
    pub bio: Option<String>,
    /// ホームチャンネルのUUID `00000000-0000-0000-0000-000000000000`を指定すると、ホームチャンネルが`null`に設定されます
    #[serde(rename = "homeChannel", skip_serializing_if = "Option::is_none")]
    pub home_channel: Option<uuid::Uuid>,
}

impl PatchMeRequest {
    /// 自分のユーザー情報変更リクエスト
    pub fn new() -> PatchMeRequest {
        PatchMeRequest {
            display_name: None,
            twitter_id: None,
            bio: None,
            home_channel: None,
        }
    }
}


