/*
 * traQ v3
 *
 * traQ v3 API
 *
 * The version of the OpenAPI document: 3.0
 * 
 * Generated by: https://openapi-generator.tech
 */

/// PostLoginRequest : ログインリクエスト



#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct PostLoginRequest {
    /// ユーザー名
    #[serde(rename = "name")]
    pub name: String,
    /// パスワード
    #[serde(rename = "password")]
    pub password: String,
}

impl PostLoginRequest {
    /// ログインリクエスト
    pub fn new(name: String, password: String) -> PostLoginRequest {
        PostLoginRequest {
            name,
            password,
        }
    }
}


