/*
 * traQ v3
 *
 * traQ v3 API
 *
 * The version of the OpenAPI document: 3.0
 * 
 * Generated by: https://openapi-generator.tech
 */

/// PostMyFcmDeviceRequest : FCMデバイス登録リクエスト



#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct PostMyFcmDeviceRequest {
    /// FCMのデバイストークン
    #[serde(rename = "token")]
    pub token: String,
}

impl PostMyFcmDeviceRequest {
    /// FCMデバイス登録リクエスト
    pub fn new(token: String) -> PostMyFcmDeviceRequest {
        PostMyFcmDeviceRequest {
            token,
        }
    }
}


