/*
 * traQ v3
 *
 * traQ v3 API
 *
 * The version of the OpenAPI document: 3.0
 * 
 * Generated by: https://openapi-generator.tech
 */

/// PostMessageRequest : メッセージ投稿リクエスト



#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct PostMessageRequest {
    /// メッセージ本文
    #[serde(rename = "content")]
    pub content: String,
    /// メンション・チャンネルリンクを自動埋め込みするか
    #[serde(rename = "embed", skip_serializing_if = "Option::is_none")]
    pub embed: Option<bool>,
}

impl PostMessageRequest {
    /// メッセージ投稿リクエスト
    pub fn new(content: String) -> PostMessageRequest {
        PostMessageRequest {
            content,
            embed: None,
        }
    }
}


