/*
 * traQ v3
 *
 * traQ v3 API
 *
 * The version of the OpenAPI document: 3.0
 * 
 * Generated by: https://openapi-generator.tech
 */

/// PostUserRequest : ユーザー登録リクエスト



#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct PostUserRequest {
    /// ユーザー名
    #[serde(rename = "name")]
    pub name: String,
    /// パスワード
    #[serde(rename = "password", skip_serializing_if = "Option::is_none")]
    pub password: Option<String>,
}

impl PostUserRequest {
    /// ユーザー登録リクエスト
    pub fn new(name: String) -> PostUserRequest {
        PostUserRequest {
            name,
            password: None,
        }
    }
}


