/*
 * traQ v3
 *
 * traQ v3 API
 *
 * The version of the OpenAPI document: 3.0
 * 
 * Generated by: https://openapi-generator.tech
 */

/// SubscribersChangedEvent : 購読者変更イベント



#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct SubscribersChangedEvent {
    /// 変更者UUID
    #[serde(rename = "userId")]
    pub user_id: uuid::Uuid,
    /// オンにされたユーザーのUUID配列
    #[serde(rename = "on")]
    pub on: Vec<uuid::Uuid>,
    /// オフにされたユーザーのUUID配列
    #[serde(rename = "off")]
    pub off: Vec<uuid::Uuid>,
}

impl SubscribersChangedEvent {
    /// 購読者変更イベント
    pub fn new(user_id: uuid::Uuid, on: Vec<uuid::Uuid>, off: Vec<uuid::Uuid>) -> SubscribersChangedEvent {
        SubscribersChangedEvent {
            user_id,
            on,
            off,
        }
    }
}


