/*
 * traQ v3
 *
 * traQ v3 API
 *
 * The version of the OpenAPI document: 3.0
 * 
 * Generated by: https://openapi-generator.tech
 */

/// ThumbnailType : サムネイル画像のタイプ 

/// サムネイル画像のタイプ 
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum ThumbnailType {
    #[serde(rename = "image")]
    Image,
    #[serde(rename = "waveform")]
    Waveform,

}

impl ToString for ThumbnailType {
    fn to_string(&self) -> String {
        match self {
            Self::Image => String::from("image"),
            Self::Waveform => String::from("waveform"),
        }
    }
}

impl Default for ThumbnailType {
    fn default() -> ThumbnailType {
        Self::Image
    }
}




