/*
 * traQ v3
 *
 * traQ v3 API
 *
 * The version of the OpenAPI document: 3.0
 * 
 * Generated by: https://openapi-generator.tech
 */

/// UserDetail : ユーザー詳細情報



#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct UserDetail {
    /// ユーザーUUID
    #[serde(rename = "id")]
    pub id: uuid::Uuid,
    #[serde(rename = "state")]
    pub state: crate::models::UserAccountState,
    /// BOTかどうか
    #[serde(rename = "bot")]
    pub bot: bool,
    /// アイコンファイルUUID
    #[serde(rename = "iconFileId")]
    pub icon_file_id: uuid::Uuid,
    /// ユーザー表示名
    #[serde(rename = "displayName")]
    pub display_name: String,
    /// ユーザー名
    #[serde(rename = "name")]
    pub name: String,
    /// Twitter ID
    #[serde(rename = "twitterId")]
    pub twitter_id: String,
    /// 最終オンライン日時
    #[serde(rename = "lastOnline", deserialize_with = "Option::deserialize")]
    pub last_online: Option<String>,
    /// 更新日時
    #[serde(rename = "updatedAt")]
    pub updated_at: String,
    /// タグリスト
    #[serde(rename = "tags")]
    pub tags: Vec<crate::models::UserTag>,
    /// 所属グループのUUIDの配列
    #[serde(rename = "groups")]
    pub groups: Vec<uuid::Uuid>,
    /// 自己紹介(biography)
    #[serde(rename = "bio")]
    pub bio: String,
    /// ホームチャンネル
    #[serde(rename = "homeChannel", deserialize_with = "Option::deserialize")]
    pub home_channel: Option<uuid::Uuid>,
}

impl UserDetail {
    /// ユーザー詳細情報
    pub fn new(id: uuid::Uuid, state: crate::models::UserAccountState, bot: bool, icon_file_id: uuid::Uuid, display_name: String, name: String, twitter_id: String, last_online: Option<String>, updated_at: String, tags: Vec<crate::models::UserTag>, groups: Vec<uuid::Uuid>, bio: String, home_channel: Option<uuid::Uuid>) -> UserDetail {
        UserDetail {
            id,
            state,
            bot,
            icon_file_id,
            display_name,
            name,
            twitter_id,
            last_online,
            updated_at,
            tags,
            groups,
            bio,
            home_channel,
        }
    }
}


