/*
 * traQ v3
 *
 * traQ v3 API
 *
 * The version of the OpenAPI document: 3.0
 * 
 * Generated by: https://openapi-generator.tech
 */

/// UserTag : ユーザータグ



#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct UserTag {
    /// タグUUID
    #[serde(rename = "tagId")]
    pub tag_id: uuid::Uuid,
    /// タグ文字列
    #[serde(rename = "tag")]
    pub tag: String,
    /// タグがロックされているか
    #[serde(rename = "isLocked")]
    pub is_locked: bool,
    /// タグ付与日時
    #[serde(rename = "createdAt")]
    pub created_at: String,
    /// タグ更新日時
    #[serde(rename = "updatedAt")]
    pub updated_at: String,
}

impl UserTag {
    /// ユーザータグ
    pub fn new(tag_id: uuid::Uuid, tag: String, is_locked: bool, created_at: String, updated_at: String) -> UserTag {
        UserTag {
            tag_id,
            tag,
            is_locked,
            created_at,
            updated_at,
        }
    }
}


