/*
 * traQ v3
 *
 * traQ v3 API
 *
 * The version of the OpenAPI document: 3.0
 * 
 * Generated by: https://openapi-generator.tech
 */

/// UserSubscribeState : ユーザーのチャンネル購読状態



#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct UserSubscribeState {
    /// チャンネルUUID
    #[serde(rename = "channelId")]
    pub channel_id: uuid::Uuid,
    #[serde(rename = "level")]
    pub level: crate::models::ChannelSubscribeLevel,
}

impl UserSubscribeState {
    /// ユーザーのチャンネル購読状態
    pub fn new(channel_id: uuid::Uuid, level: crate::models::ChannelSubscribeLevel) -> UserSubscribeState {
        UserSubscribeState {
            channel_id,
            level,
        }
    }
}


