/*
 * traQ v3
 *
 * traQ v3 API
 *
 * The version of the OpenAPI document: 3.0
 * 
 * Generated by: https://openapi-generator.tech
 */

/// Version : バージョン・サーバーフラグ情報



#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct Version {
    /// traQ(サーバー)リビジョン
    #[serde(rename = "revision")]
    pub revision: String,
    /// traQ(サーバー)バージョン
    #[serde(rename = "version")]
    pub version: String,
    #[serde(rename = "flags")]
    pub flags: Box<crate::models::VersionFlags>,
}

impl Version {
    /// バージョン・サーバーフラグ情報
    pub fn new(revision: String, version: String, flags: crate::models::VersionFlags) -> Version {
        Version {
            revision,
            version,
            flags: Box::new(flags),
        }
    }
}


