/*
 * traQ v3
 *
 * traQ v3 API
 *
 * The version of the OpenAPI document: 3.0
 * 
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct WebRtcUserStateSessionsInner {
    /// 状態
    #[serde(rename = "state")]
    pub state: String,
    /// セッションID
    #[serde(rename = "sessionId")]
    pub session_id: String,
}

impl WebRtcUserStateSessionsInner {
    pub fn new(state: String, session_id: String) -> WebRtcUserStateSessionsInner {
        WebRtcUserStateSessionsInner {
            state,
            session_id,
        }
    }
}


