/*
 * traQ v3
 *
 * traQ v3 API
 *
 * The version of the OpenAPI document: 3.0
 * 
 * Generated by: https://openapi-generator.tech
 */

/// ActivityTimelineMessage : Timelineアクテビティ用メッセージ



#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct ActivityTimelineMessage {
    /// メッセージUUID
    #[serde(rename = "id")]
    pub id: uuid::Uuid,
    /// 投稿者UUID
    #[serde(rename = "userId")]
    pub user_id: uuid::Uuid,
    /// チャンネルUUID
    #[serde(rename = "channelId")]
    pub channel_id: uuid::Uuid,
    /// メッセージ本文
    #[serde(rename = "content")]
    pub content: String,
    /// 投稿日時
    #[serde(rename = "createdAt")]
    pub created_at: String,
    /// 編集日時
    #[serde(rename = "updatedAt")]
    pub updated_at: String,
}

impl ActivityTimelineMessage {
    /// Timelineアクテビティ用メッセージ
    pub fn new(id: uuid::Uuid, user_id: uuid::Uuid, channel_id: uuid::Uuid, content: String, created_at: String, updated_at: String) -> ActivityTimelineMessage {
        ActivityTimelineMessage {
            id,
            user_id,
            channel_id,
            content,
            created_at,
            updated_at,
        }
    }
}


