/*
 * traQ v3
 *
 * traQ v3 API
 *
 * The version of the OpenAPI document: 3.0
 *
 * Generated by: https://openapi-generator.tech
 */

/// BotEventLog : BOTイベントログ

#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct BotEventLog {
    /// BOT UUID
    #[serde(rename = "botId")]
    pub bot_id: uuid::Uuid,
    /// リクエストUUID
    #[serde(rename = "requestId")]
    pub request_id: uuid::Uuid,
    /// イベントタイプ
    #[serde(rename = "event")]
    pub event: String,
    #[serde(rename = "result", skip_serializing_if = "Option::is_none")]
    pub result: Option<crate::openapi::models::BotEventResult>,
    /// ステータスコード
    #[serde(rename = "code")]
    pub code: i32,
    /// イベント日時
    #[serde(rename = "datetime")]
    pub datetime: String,
}

impl BotEventLog {
    /// BOTイベントログ
    pub fn new(
        bot_id: uuid::Uuid,
        request_id: uuid::Uuid,
        event: String,
        code: i32,
        datetime: String,
    ) -> BotEventLog {
        BotEventLog {
            bot_id,
            request_id,
            event,
            result: None,
            code,
            datetime,
        }
    }
}
