/*
 * traQ v3
 *
 * traQ v3 API
 *
 * The version of the OpenAPI document: 3.0
 * 
 * Generated by: https://openapi-generator.tech
 */

/// BotMode : BOT動作モード  HTTP: HTTP Mode WebSocket: WebSocket Mode

/// BOT動作モード  HTTP: HTTP Mode WebSocket: WebSocket Mode
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum BotMode {
    #[serde(rename = "HTTP")]
    HTTP,
    #[serde(rename = "WebSocket")]
    WebSocket,

}

impl ToString for BotMode {
    fn to_string(&self) -> String {
        match self {
            Self::HTTP => String::from("HTTP"),
            Self::WebSocket => String::from("WebSocket"),
        }
    }
}

impl Default for BotMode {
    fn default() -> BotMode {
        Self::HTTP
    }
}




