/*
 * traQ v3
 *
 * traQ v3 API
 *
 * The version of the OpenAPI document: 3.0
 * 
 * Generated by: https://openapi-generator.tech
 */


/// 
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum OAuth2Prompt {
    #[serde(rename = "none")]
    None,

}

impl ToString for OAuth2Prompt {
    fn to_string(&self) -> String {
        match self {
            Self::None => String::from("none"),
        }
    }
}

impl Default for OAuth2Prompt {
    fn default() -> OAuth2Prompt {
        Self::None
    }
}




