/*
 * traQ v3
 *
 * traQ v3 API
 *
 * The version of the OpenAPI document: 3.0
 * 
 * Generated by: https://openapi-generator.tech
 */

/// PatchWebhookRequest : Webhook情報変更リクエスト



#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct PatchWebhookRequest {
    /// Webhookユーザー表示名
    #[serde(rename = "name", skip_serializing_if = "Option::is_none")]
    pub name: Option<String>,
    /// 説明
    #[serde(rename = "description", skip_serializing_if = "Option::is_none")]
    pub description: Option<String>,
    /// デフォルトの投稿先チャンネルUUID
    #[serde(rename = "channelId", skip_serializing_if = "Option::is_none")]
    pub channel_id: Option<uuid::Uuid>,
    /// Webhookシークレット
    #[serde(rename = "secret", skip_serializing_if = "Option::is_none")]
    pub secret: Option<String>,
    /// 移譲先のユーザーUUID
    #[serde(rename = "ownerId", skip_serializing_if = "Option::is_none")]
    pub owner_id: Option<uuid::Uuid>,
}

impl PatchWebhookRequest {
    /// Webhook情報変更リクエスト
    pub fn new() -> PatchWebhookRequest {
        PatchWebhookRequest {
            name: None,
            description: None,
            channel_id: None,
            secret: None,
            owner_id: None,
        }
    }
}


