/*
 * traQ v3
 *
 * traQ v3 API
 *
 * The version of the OpenAPI document: 3.0
 *
 * Generated by: https://openapi-generator.tech
 */

/// PatchUserRequest : ユーザー情報編集リクエスト

#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct PatchUserRequest {
    /// 新しい表示名
    #[serde(rename = "displayName", skip_serializing_if = "Option::is_none")]
    pub display_name: Option<String>,
    /// TwitterID
    #[serde(rename = "twitterId", skip_serializing_if = "Option::is_none")]
    pub twitter_id: Option<String>,
    #[serde(rename = "state", skip_serializing_if = "Option::is_none")]
    pub state: Option<crate::openapi::models::UserAccountState>,
    /// ユーザーロール
    #[serde(rename = "role", skip_serializing_if = "Option::is_none")]
    pub role: Option<String>,
}

impl PatchUserRequest {
    /// ユーザー情報編集リクエスト
    pub fn new() -> PatchUserRequest {
        PatchUserRequest {
            display_name: None,
            twitter_id: None,
            state: None,
            role: None,
        }
    }
}
