/*
 * traQ v3
 *
 * traQ v3 API
 *
 * The version of the OpenAPI document: 3.0
 * 
 * Generated by: https://openapi-generator.tech
 */

/// PatchGroupMemberRequest : ユーザーグループメンバー編集リクエスト



#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct PatchGroupMemberRequest {
    /// ユーザーの役割
    #[serde(rename = "role")]
    pub role: String,
}

impl PatchGroupMemberRequest {
    /// ユーザーグループメンバー編集リクエスト
    pub fn new(role: String) -> PatchGroupMemberRequest {
        PatchGroupMemberRequest {
            role,
        }
    }
}


