/*
 * traQ v3
 *
 * traQ v3 API
 *
 * The version of the OpenAPI document: 3.0
 * 
 * Generated by: https://openapi-generator.tech
 */

/// PostStampPaletteRequest : スタンプパレット作成リクエスト



#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct PostStampPaletteRequest {
    /// パレット内のスタンプのUUID配列
    #[serde(rename = "stamps")]
    pub stamps: Vec<uuid::Uuid>,
    /// パレット名
    #[serde(rename = "name")]
    pub name: String,
    /// 説明
    #[serde(rename = "description")]
    pub description: String,
}

impl PostStampPaletteRequest {
    /// スタンプパレット作成リクエスト
    pub fn new(stamps: Vec<uuid::Uuid>, name: String, description: String) -> PostStampPaletteRequest {
        PostStampPaletteRequest {
            stamps,
            name,
            description,
        }
    }
}


