/*
 * traQ v3
 *
 * traQ v3 API
 *
 * The version of the OpenAPI document: 3.0
 *
 * Generated by: https://openapi-generator.tech
 */

/// PostBotRequest : BOT作成リクエスト

#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct PostBotRequest {
    /// BOTユーザーID 自動的に接頭辞\"BOT_\"が付与されます
    #[serde(rename = "name")]
    pub name: String,
    /// BOTユーザー表示名
    #[serde(rename = "displayName")]
    pub display_name: String,
    /// BOTの説明
    #[serde(rename = "description")]
    pub description: String,
    #[serde(rename = "mode")]
    pub mode: crate::openapi::models::BotMode,
    /// BOTサーバーエンドポイント BOT動作モードがHTTPの場合必須です
    #[serde(rename = "endpoint", skip_serializing_if = "Option::is_none")]
    pub endpoint: Option<String>,
}

impl PostBotRequest {
    /// BOT作成リクエスト
    pub fn new(
        name: String,
        display_name: String,
        description: String,
        mode: crate::openapi::models::BotMode,
    ) -> PostBotRequest {
        PostBotRequest {
            name,
            display_name,
            description,
            mode,
            endpoint: None,
        }
    }
}
