/*
 * traQ v3
 *
 * traQ v3 API
 *
 * The version of the OpenAPI document: 3.0
 * 
 * Generated by: https://openapi-generator.tech
 */

/// PutUserPasswordRequest : ユーザーパスワード変更リクエスト



#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct PutUserPasswordRequest {
    /// 新しいパスワード
    #[serde(rename = "newPassword")]
    pub new_password: String,
}

impl PutUserPasswordRequest {
    /// ユーザーパスワード変更リクエスト
    pub fn new(new_password: String) -> PutUserPasswordRequest {
        PutUserPasswordRequest {
            new_password,
        }
    }
}


