/*
 * traQ v3
 *
 * traQ v3 API
 *
 * The version of the OpenAPI document: 3.0
 * 
 * Generated by: https://openapi-generator.tech
 */

/// UserSettings : ユーザー設定の情報



#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct UserSettings {
    /// ユーザーUUID
    #[serde(rename = "id")]
    pub id: uuid::Uuid,
    /// メッセージ引用通知の設定情報
    #[serde(rename = "notifyCitation")]
    pub notify_citation: bool,
}

impl UserSettings {
    /// ユーザー設定の情報
    pub fn new(id: uuid::Uuid, notify_citation: bool) -> UserSettings {
        UserSettings {
            id,
            notify_citation,
        }
    }
}


